---

- name: Configuring module
  template:
    src: "{{ newrelic_config_template }}"
    dest: "/etc/newrelic/nrsysmond.cfg"
    owner: "{{ newrelic_user }}"
    group: "{{ newrelic_group }}"
    mode: "0640"
  notify: restart newrelic

- name: Configuring user groups
  user:
    name: "{{ newrelic_user }}"
    groups: "{{ newrelic_groups|join(',') }}"
    append: yes
  when: not newrelic_disable_docker
